# for this playbook, remote host must have acl package installed. ex: apt install acl
# run command: ansible-playbook postgresql.yaml -i hosts
---
- hosts: all
  become: yes
  become_flags: "-E"
  become_user: "{{ remote_user_name }}"
  gather_facts: no

  vars_files:
    - pg_vars.yaml

  tasks:
    - name: "Set timestamp for the backup"
      set_fact:
        now: "{{ lookup('pipe', 'date +%F-%T') }}"
    - name: "Create a backup directory"
      with_items: "{{ db_name }}"
      file:
        path: "/home/{{ remote_user_name }}/db_backup/{{ item }}/{{ now }}/"
        mode: 0777
        owner: "{{ remote_user_name }}"
        state: directory
    - name: "Back up the database"
      with_items: "{{ db_name }}"
      postgresql_db:
        state: dump
        name: "{{ item }}"
        login_host: "{{ pg_host }}"
        login_user: "{{ pg_user }}"
        login_password: "{{ pg_password }}"
        target: "/home/{{ remote_user_name }}/db_backup/{{ item }}/{{ now }}/{{ item }}.dump.gz"

    - name: "Fetch backup from the server"
      with_items: "{{ db_name }}"
      fetch:
        src: "/home/{{ remote_user_name }}/db_backup/{{ item }}/{{ now }}/{{ item }}.dump.gz"
        dest: "backups/{{ item }}/{{ now }}/{{ item }}.dump.gz"
        flat: yes
